### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by josefmonje** [erllypaguntalan/pythreads_lele#2]
missing requirements.txt file :package:

**Comment by erllypaguntalan** [comment]
Done

**Comment by josefmonje** [comment]
## using get request to change objects: review http request methods/RESTful services/ajax

```
@app.route('/delete_comment/<int:id>')
@login_required
def delete_comment(id):
    comment = Comment.query.get(id)
    if comment is None:
        flash('Comment not found.')
        return redirect(url_for('index'))
    if comment.c_author.id != g.user.id:
        flash('You cannot delete this comment.')
        return redirect(url_for('thread', id=comment.thread_id))
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted.')
    return redirect(url_for('thread', id=comment.thread_id))
```

get is used only for reading/retrieving resources. in the example, `get` deletes a resource.

consider, for example, a crawler/spider or wrong click/tap. it deletes your data just by visiting the url.

## unnecessary decorators

```
@app.route('/user/<nickname>')
@app.route('/user/<nickname>', methods=['GET', 'POST'])
```

the first `@app.route` is unnecessary

## code repetition

```
        comment = Comment(body=form.body.data, date_created=datetime.utcnow(), c_author=g.user, c_thread=thread)
        db.session.add(comment)
        db.session.commit()
```

consider making these lines part of a model's method. that way, all database interaction (since they all work the same way) would be in your models. any database concern can easily be found within your models, not mixed in your view functions. also, your usage of models would, for example, look like: 

```
class Comment(db.Model):
    ...

    def save...
```

```
    comment = Comment(body=form.body.data, date_created=datetime.utcnow(), c_author=g.user, c_thread=thread)
    comment.save()
```

study pep8 to learn python coding guidelines :)

**Comment by erllypaguntalan** [comment]
change GET request method to POST --- DONE
remove unnecessary decorators --- DONE
db.session.add/delete/commit method --- DONE
